name: Backend CI

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  setup:
    name: Setup JDK and Grant Gradle Permission
    runs-on: ubuntu-latest
    outputs:
      gradle_cache_hit: ${{ steps.cache-gradle.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: 21
      - name: Grant Gradle permission
        run: chmod +x ./gradlew
      - name: Cache Gradle Wrapper
        uses: actions/cache@v3
        id: cache-gradle-wrapper
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        id: cache-gradle
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('build.gradle.kts', 'build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

  lint:
    name: Lint
    needs: setup
    if: github.ref == 'refs/heads/develop' || github.base_ref == 'develop'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3 # 필요하다면 유지
      - name: Checkstyle
        run: ./gradlew checkstyleMain

  unit:
    name: Unit Test
    needs: setup
    if: github.ref == 'refs/heads/develop' || github.base_ref == 'develop'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3 # 필요하다면 유지
      - name: Run Tests
        run: ./gradlew test

  integration-test:
    name: Integration Test
    needs: setup
    if: github.base_ref == 'main' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3 # 필요하다면 유지
      - name: Start Spring Boot App
        run: ./gradlew bootRun &
        env:
          SPRING_PROFILES_ACTIVE: test # 테스트 환경 활성화 (선택 사항)
      - name: Wait for App to Start
        run: |
          TIMEOUT=60
          for i in $(seq 1 $TIMEOUT); do
            if curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/actuator/health | grep -q '"status":"UP"'; then
              echo "Application is ready"
              exit 0
            fi
            echo "Waiting for application... ($i/$TIMEOUT)"
            sleep 1
          done
          echo "Application did not start within the timeout"
          exit 1
      - name: Integration Test
        run: |
          ./gradlew integrationTest
          curl -X GET http://localhost:8080/api/challenges/events
          curl -X GET http://localhost:8080/api/challenges/personal
      - name: Stop Spring Boot App
        run: pkill -f 'org.springframework.boot.loader.JarLauncher' # 또는 애플리케이션 실행 방식에 따른 프로세스 종료

  build-dev:
    name: Build (develop only)
    needs: [lint, unit, setup]
    if: github.ref == 'refs/heads/develop' || github.base_ref == 'develop'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3 # 필요하다면 유지
      - name: Build
        run: ./gradlew build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: be-build-dev
          path: backend/build/libs/

  build-prod:
    name: Build (main only PR)
    needs: [integration-test, setup]
    if: github.base_ref == 'main' && github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3 # 필요하다면 유지
      - name: Build
        run: ./gradlew build
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: be-build-prod
          path: backend/build/libs/
